# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        your_db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            # http://symfony.com/doc/current/security/guard_authentication.html
            guard:
                authenticators:
                    - AppBundle\Security\VkontakteAuthenticator
        # if you want, disable storing the user in the session
        # stateless: true

        # maybe other things, like form_login, remember_me, etc
        # ...